### ISSUE TITLE
Application doesn't connect to https

### ISSUE THREAD

**Issue by sinaone1** [uhm0311/SocketIOSharp#14]
Hello
I created a test application and it works very well on local host in my pc but when I test it by https on our server it doesn't give me any feedback even error .
I attached both server side and client side here so you could check both.
Thank you
[Server Side.zip](https://github.com/uhm0311/SocketIOSharp/files/7013115/Server.Side.zip)
[Client Test.zip](https://github.com/uhm0311/SocketIOSharp/files/7013119/Client.Test.zip)

**Comment by yylyhl** [comment]
> Hello I created a test application and it works very well on local host in my pc but when I test it by https on our server it doesn't give me any feedback even error . I attached both server side and client side here so you could check both. Thank you [Server Side.zip](https://github.com/uhm0311/SocketIOSharp/files/7013115/Server.Side.zip) [Client Test.zip](https://github.com/uhm0311/SocketIOSharp/files/7013119/Client.Test.zip)

Is...solved?

**Comment by sinaone1** [comment]
Yes problem was not https  problem was about litespeed , now I have it installed on my cpanel and everything works very well
