### ISSUE TITLE
SocketIOClient.Event is inaccessible due to its protection level

### ISSUE THREAD

**Issue by Giv0** [uhm0311/SocketIOSharp#2]
i copied the example code of 
```
client.On(SocketIOClient.Event.CONNECTION, () =>
{
   Console.WriteLine("Connected!");
});
```
and i get this error

**Comment by Giv0** [comment]
nm i got it fixed

**Comment by harithzamri** [comment]
@Giv0 I am facing the same problem, can I know how you manage to solve it?

**Comment by OfficialLahusa** [comment]
> 
> 
> nm i got it fixed

How did you fix it? @Giv0
